---
title: "Otter - Vega"
author: "Markus Fjellstad Israelsen"
date: "22 12 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

Load library
```{r Library, echo = FALSE}

library(dplyr)
library(rgdal)
library(raster)
library(rgeos)
library(spatial)
library(maptools)
library(readxl)
library(writexl)
library(lubridate)
library(sp)

```

Load data
```{r Datasets}

coastlineVega = terra::vect("C:/Users/markus.israelsen/OneDrive - NINA/Oter/Vega/R-mappe - Kystkontur/Coastline/coastlineVegaLength.shp")
coastlineMudd = terra::vect("C:/Users/markus.israelsen/OneDrive - NINA/Oter/Vega/R-mappe - Kystkontur/Coastline/CoastlineMuddvaeretLength.shp")
coastlineMuddPoints = terra::vect("C:/Users/markus.israelsen/OneDrive - NINA/Oter/Vega/R-mappe - Kystkontur/Coastline/CoastlineMuddvaeretPointsLength.shp")

plot(coastlineMudd)
plot(coastlineMuddPoints, col = "red", add = TRUE)

vegaCoastlineKM = sum(coastlineVega$length)/1000
muddTotalCoastlineKM = sum(coastlineMudd$length)/1000
muddCoastlineKM = sum(coastlineMuddPoints$length)/1000

otterPointsRaw = read_xlsx("C:/Users/markus.israelsen/OneDrive - NINA/Oter/Vega/OnlyVegaMuddRawConverted.xlsx")

# Number of otters per 10km coastline
# Group by year & area
# count the number of otter observations and divide by the length of the coastline
otterPointsRaw = otterPointsRaw %>% mutate(Year = year(Date), Counter = 1)
otterPointsMudd = otterPointsRaw %>% filter(`Sub-Area` == "Muddværet") 
otterPointsVega = otterPointsRaw %>% filter(`Sub-Area` != "Muddværet")

opVegaCoords = cbind(as.numeric(otterPointsVega$UTM_X), as.numeric(otterPointsVega$UTM_Y))
opVegaSP = SpatialPoints(opVegaCoords, proj4string = CRS("+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))

plot(coastlineVega)
plot(opVegaSP, add = TRUE, col = "steelblue", pch = 18)

opMuddCoords = cbind(as.numeric(otterPointsMudd$UTM_X), as.numeric(otterPointsMudd$UTM_Y))
opMuddSP = SpatialPoints(opMuddCoords, proj4string = CRS("+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))

plot(coastlineMudd)
plot(opMuddSP, add = TRUE, col = "magenta", pch = 18)

opVega = otterPointsVega %>% group_by(Year) %>% summarise(Counts = sum(Counter))
opMudd = otterPointsMudd %>% group_by(Year) %>% summarise(Counts = sum(Counter))


cbind(opVega, OtterPerKM = opVega$Counts/vegaCoastlineKM, OtterPer10KM = (opVega$Counts/vegaCoastlineKM)*10)

cbind(opMudd, OtterPerKM = opMudd$Counts/muddTotalCoastlineKM, OtterPer10KM = (opMudd$Counts/muddTotalCoastlineKM)*10)

cbind(opMudd, OtterPerKM = opMudd$Counts/muddCoastlineKM, OtterPer10KM = (opMudd$Counts/muddCoastlineKM)*10)

# Control for individuals - Vega
otterPointsVega19 = otterPointsVega %>% filter(year(Date) == 2019)
otterPointsVega20 = otterPointsVega %>% filter(year(Date) == 2020)
otterPointsVega20NA = otterPointsVega20 %>% filter(is.na(IndividID))
otterPointsVega20NotNA = otterPointsVega20[which(!duplicated(otterPointsVega20$IndividID)), ]
otterPointsVega20NotNA = otterPointsVega20NotNA[-1, ]

otterPointsVega2020 = rbind(otterPointsVega20NA, otterPointsVega20NotNA)
otterPointsVega = rbind(otterPointsVega19, otterPointsVega2020)

# Control for individuals - Muddværet
otterPointsMudd19 = otterPointsMudd %>% filter(year(Date) == 2019)
otterPointsMudd20 = otterPointsMudd %>% filter(year(Date) == 2020)


```

